services:
  - type: web
    name: flaskmyapp
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
